#!/usr/bin/env python3
# coding=utf-8

from src.utm import argument_parser_pyinquirer, TuringMachine
import json


def main():
    requested_args = argument_parser_pyinquirer()
    try:
        transitions = json.loads(open(requested_args['transitions']).read())
        turing_machine = TuringMachine(transitions,
                               requested_args['input_tape'],
                               requested_args['start_state'],
                               requested_args['end_state'],
                               requested_args['speed'],
                               requested_args['rendered_tape_length']).run()
        print()
        print('Input: {}'.format(requested_args.input_tape))
        print('Output: {}'.format(turing_machine))
        print('The Turing Machine answered YES')
    except Exception as e:
        print('Something went wrong! Issue: {}'.format(e))
        print()
        print('The Turing Machine answered NO')
        print()

if __name__ == '__main__':
    main()
